language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1.100
braches:
    - only:
        - master 
# before script:
#     - dotnet restore Travis_test_API/Travis_test_API/
# before_script:
#     - chmod -R a+x scripts

script:
    - dotnet build ./Travis_test_API/
    - dotnet test ./Travis_test_API/
# branches:
#     only: 
#         - master
#         - /.*/
# before_script:
#     - chmod -R a+x scripts

# install:
# - dotnet restore

# script:
# - dotnet build