language: csharp
os: linux
dist: xenial
sudo: true
mono: none
dotnet: 3.1.1
braches:
    - only:
        - master 
# before script:
#     - dotnet restore Travis_test_API/Travis_test_API/
script:
    - dotnet build Travis_test_API/
# branches:
#     only: 
#         - master
#         - /.*/
# before_script:
#     - chmod -R a+x scripts

# install:
# - dotnet restore

# script:
# - dotnet build